name: FastAPI Multi-App CI

on:
  pull_request:
    # Optionally, specify target branches
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build app1
        run: docker build -t app1-fastapi ./backend1

      - name: Build app2
        run: docker build -t app2-fastapi ./backend2
